!!omap
- OUTPUT_DIR: exp_V+Conv2D-BiLSTM+PHQ-Score
- SAVE_CONFIG_NAME: config_V+Conv2D-BiLSTM+PHQ-Score.yaml
- CKPTS_DIR: /mnt/wd1/cv_dep/2017/wpingcheng/ckpts_new/
- TYPE: V+Conv2D-BiLSTM+PHQ-Score
- MANUAL_SEED: 1
- LOG_TITLE: Depression Detection with visual features (key points & gaze direction),
    Conv2D-BiLSTM, PHQ-Score, CrossEntropy with weights, ASAM
- DATA: !!omap
  - TRAIN_ROOT_DIR: /mnt/wd1/cv_dep/2017/wpingcheng/DAIC_WOZ-generated_database_V2/train/clipped_data/
  - VALIDATION_ROOT_DIR: /mnt/wd1/cv_dep/2017/wpingcheng/DAIC_WOZ-generated_database_V2/train/clipped_data/
  - TEST_ROOT_DIR: /mnt/wd1/cv_dep/2017/wpingcheng/DAIC_WOZ-generated_database_V2/test/clipped_data/
  - USE_MEL_SPECTROGRAM: false
  - VISUAL_WITH_GAZE: true
  - PADDING:
  - RESCALE_SIZE:
  - CROP_SIZE:
  - BATCH_SIZE: 64
  - NUM_WORKERS: 0
- MODEL: !!omap
  - PHQ_THRESHOLD: 10
  - EPOCHS: 200
  - WEIGHTS: !!omap
    - TYPE: new
    - DATE:
    - PATH: model_weights
    - NAME:
    - CUSTOM_ABSOLUTE_PATH:
    - INCLUDED:
  - VISUAL_NET: !!omap
    - INPUT_DIM: 3
    - CONV_HIDDEN: 256
    - LSTM_HIDDEN: 256
    - OUTPUT_DIM: 256
    - NUM_LAYERS: 4
    - ACTIVATION: relu
    - NORM: bn
    - DROPOUT: 0.5
  - EVALUATOR: !!omap
    - PREDICT_TYPE: phq-score
    - INPUT_FEATURE_DIM: 256
    - CLASSES_RESOLUTION: 25
    - N_CLASSES: 25
    - N_SUBSCORES: 8
    - STD: 5
  - CRITERION: !!omap
    - USE_SOFT_LABEL: false
    - USE_WEIGHTS: true
  - OPTIMIZER: !!omap
    - LR: 0.001
    - WEIGHT_DECAY: 0.0001
    - USE_SAM: false
  - SCHEDULER: !!omap
    - STEP_SIZE: 10
    - GAMMA: 0.9
